model_name: "TagInsert"
bert_model: "distilbert/distilbert-base-cased"
device: "cuda"
lr: 0.5
betas: [0.9, 0.98]
eps: 0.000000001
warmup: 400
n_stacks: 8
n_heads: 8
batch_size: 8
epochs: 3
block_size: 52
bert_block_size: 100
hidden_size: 768